spring:
  datasource:
    schema: classpath:import.sql
  output:
    ansi:
      enabled: detect
  profiles:
    active: dev


#logging:
#  level:
#    root: debug
#    org.houqian: info
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level RequestID:%X{Request_ID} %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level RequestID:%X{Request_ID} %logger{36} - %msg%n"
---
spring:
  profiles: dev

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite

simpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=dShanghai,2=Guangzhou

dataflowJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

kafka:
  bootstrap-servers: localhost:9092
