spring:
  datasource:
    schema: classpath:import.sql
  output:
    ansi:
      enabled: detect
  profiles:
    active: @activeProfile@

---
spring:
  profiles: dev

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite

simpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

dataflowJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou